import Head from 'next/head'
import Link from 'next/link'

import '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Love Test</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <div className="home--page">
        <ul>
          <li>About The Test</li>
          <li>
            <Link href={'/test/settings'}>Lets Start</Link>
          </li>
          <li>Who am i ?</li>
        </ul>
      </div>
      <div className="do--not--show"></div>
    </>
  )
}
