import Head from "next/head"
import Link from "next/link"

import { useState } from "react"

import "../styles/Home.module.css"

export default function Home() {
  const [showAbout, setShowAbout] = useState<string>("")
  const [isActive, setIsActive] = useState<boolean>(false)
  const [isActive2, setIsActive2] = useState<boolean>(false)

  function handleAbout(e: any) {
    e.preventDefault()
    setShowAbout(e.target.innerText)
    e.target.innerText === "About The Test"
      ? setIsActive(true)
      : setIsActive(false)
    e.target.innerText === "Who am i ?"
      ? setIsActive2(true)
      : setIsActive2(false)
    console.log(e.target.innerText)
  }

  function handleLeave(e: any) {
    setShowAbout("")
    setIsActive(false)
    setIsActive2(false)
  }
  return (
    <>
      <Head>
        <title>Love Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="page home">
        <div className="page-home-container">
          <div className="main-box--container">
            <button
              className="main-box one"
              onMouseEnter={(e) => handleAbout(e)}
              onMouseLeave={handleLeave}
            >
              About The Test
            </button>
            <button className="main-box two">
              <Link href={"/test/settings"}>Lets Start</Link>
            </button>
            <button
              className="main-box three"
              onMouseEnter={(e) => handleAbout(e)}
              onMouseLeave={handleLeave}
            >
              Who am i ?
            </button>
          </div>
          <div className="main-box--container right about">
            {/* {showAbout === "About The Test" && ( */}
            <p
              className={
                isActive
                  ? "main-box four about"
                  : "main-box four about inActive"
              }
            >
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nulla
              quasi porro quisquam. Eveniet, quibusdam quidem! Quis voluptates
              animi facilis iusto, aut, possimus facere sunt sapiente
              praesentium expedita adipisci dolor. Iure, cupiditate autem
              similique sit quia dolore modi perspiciatis suscipit laboriosam
              inventore sequi dicta sapiente accusamus ad fugiat pariatur
              tempore dolores?
            </p>
            {/* )} */}
            {/* {showAbout === "Who am i ?" && ( */}
            <p
              className={
                isActive2
                  ? "main-box five about"
                  : "main-box five about inActive"
              }
            >
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta
              quos quae aut! Reprehenderit odit, earum repellendus veritatis
              error architecto incidunt at obcaecati excepturi nostrum! Natus
              obcaecati expedita quam porro hic pariatur tenetur reiciendis
              voluptatem nostrum consectetur officia animi rem aliquam culpa,
              qui cumque quisquam a doloribus ab similique! Quae, pariatur.
            </p>
            {/* )} */}
          </div>
        </div>
      </div>
      <div className="do--not--show"></div>
    </>
  )
}
