import Head from "next/head"
import Link from "next/link"

import { useState } from "react"

export default function Home() {
  const [isActive, setIsActive] = useState<boolean>(false)
  const [isActive2, setIsActive2] = useState<boolean>(false)

  function handleAbout(e: any) {
    e.preventDefault()
    e.target.innerText === "ABOUT THE TEST"
      ? setIsActive(true)
      : setIsActive(false)
    e.target.innerText === "WHO AM I ?"
      ? setIsActive2(true)
      : setIsActive2(false)
    console.log(e.target.innerText)
  }

  function handleLeave(e: any) {
    setIsActive(false)
    setIsActive2(false)
  }
  return (
    <>
      <Head>
        <title>Love Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="page home">
        <div className="page-home-container">
          <div className="main-box--container">
            <button
              className="main-box one"
              onClick={(e) => handleAbout(e)}
              onMouseLeave={handleLeave}
            >
              About The Test
            </button>
            <Link href={"/test/settings"}>
              <button className="main-box two">Lets Start</button>
            </Link>
            <button
              className="main-box three"
              onClick={(e) => handleAbout(e)}
              onMouseLeave={handleLeave}
            >
              Who am i ?
            </button>
          </div>
          <div className="main-box--container right about">
            {/* {showAbout === "About The Test" && ( */}
            <p
              className={
                isActive
                  ? "main-box four about"
                  : "main-box four about inActive"
              }
            >
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nulla
              quasi porro quisquam. Eveniet, quibusdam quidem! Quis voluptates
              animi facilis iusto, aut, possimus facere sunt sapiente
              praesentium expedita adipisci dolor. Quisquam, quae.
            </p>
            {/* )} */}
            {/* {showAbout === "Who am i ?" && ( */}
            <p
              className={
                isActive2
                  ? "main-box five about"
                  : "main-box five about inActive"
              }
            >
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta
              quos quae aut! Reprehenderit odit, earum repellendus veritatis
              error architecto incidunt at obcaecati excepturi nostrum! Natus
              obcaecati expedita quam porro hic pariatur tenetur reiciendis
            </p>
            {/* )} */}
          </div>
        </div>
      </div>
      <div className="do--not--show"></div>
    </>
  )
}
